In [1]:
import pandas as pd

In [2]:
import os

In [5]:
os.chdir("C:\Users\EdizOzdil\Downloads")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2062004320.py, line 1)

In [11]:
index=pd.read_csv("TechnologyIndex.csv",index_col="Country")

In [12]:
index

,Rank,iPhone,Android,MacBook,Windows Powered,PS4,Xbox one,iPad mini,Samsung tablet,40 inch smart TV,Apple Watch,Brand headphone,hard drive 2TB,Portable charger,Printer
Country,,,,,,,,,,,,,,,
Kuwait,1,$641.50,$539.18,$795.38,$528.34,$315.83,$418.50,$242.90,$250.98,$383.60,$242.90,$196.95,$89.03,$2.44,$52.36
Saudi Arabia,2,$513.86,$699.61,"$1,054.98",$686.88,$317.86,$254.24,$380.47,$152.44,$406.93,$381.48,$338.22,$114.27,$4.83,$30.03
Malaysia,3,$532.06,$631.66,"$1,010.31","$1,022.67",$299.83,$355.47,$232.87,$354.99,$324.87,$248.43,$175.48,$116.16,$11.41,$108.69
Canada,4,$555.25,$625.04,"$1,118.10","$1,081.40",$274.25,$233.14,$237.34,$392.89,$364.30,$259.21,$159.71,$87.12,$9.24,$57.13
United Arab Emirates,5,$498.25,$592.31,"$1,073.30","$1,026.68",$324.72,$285.72,$259.71,$311.71,$467.68,$285.71,$181.73,$84.49,$10.13,$95.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Guatemala,68,$889.56,$591.31,"$1,525.26","$2,055.53",$535.11,$341.96,$699.26,$424.11,$457.76,$508.51,$381.22,$131.32,$25.20,$144.91
Brazil,69,$843.30,$948.74,"$3,390.96",$564.91,$565.20,$425.09,$525.04,$297.18,$810.67,$383.39,$237.98,$216.85,$2.23,$112.74
Brunei,70,$764.02,$856.47,"$2,326.47","$1,545.52",$562.67,$737.90,$387.77,$660.51,$388.83,$679.29,$523.69,$192.76,$105.14,$212.22
Angola,71,$401.94,"$2,641.01","$1,001.06","$1,574.17",$868.75,$528.11,$551.84,"$1,054.42","$1,405.90",$430.88,$219.97,$274.15,$54.22,$143.48
Venezuela,72,"$97,813.82","$78,054.19","$176,005.34","$35,941.09","$56,723.53","$37,073.79","$31,228.64","$45,904.12","$119,321.58","$48,810.16",$733.68,"$14,386.04",$371.87,"$6,653.44"